// Generated by https://quicktype.io

import { User } from "../auth";
import { Post } from '../postImage/createdPost';

export interface CreateComment {
    createComment: CreateCommentClass;
}

export interface CreateCommentClass {
    message: string;
    comment: Comment;
}

export interface Comment {
    description: string;
    id:          number;
    post:        Pick<Post, 'id'>;
    user:        Pick<User, 'id'| 'name'>;
}
