import { Post } from './createdPost';
// Generated by https://quicktype.io

export interface GetFavorite {
    getIsFavorite: GetIsFavorite | null;
}

export interface GetIsFavorite {
    type: string;
    post: Pick<Post, 'id'>;
}

