// Generated by https://quicktype.io

export interface GetSortByLikes {
    data: Data;
}

export interface Data {
    getPostSortByLikes: GetPostSortByLike[];
}

export interface GetPostSortByLike {
    user:        User;
    description: string;
    url_image:   string;
    id:          number;
}

export interface User {
    id: number;
}


