export interface AuthState {
    uid: string | number | null;
    checking: boolean;
    logged: boolean;
    name: string | null;
    email: string | null;
}

export interface AuthContextProps {
    auth: AuthState;
    setAuthentication: ({ token, user }: Pick<DataAuth, "token" | "user">) => void;
    setLogout: () => Promise<void>;
    verifyToken: () => Promise<void>;
}


// Generated by https://quicktype.io
export interface User {
    email: string;
    id:    number;
    name:  string;
}

export type AuthResponse = {
    [key in 'login' | 'createUser']: DataAuth;
};


export interface DataAuth {
    token:   string;
    message: string;
    user:    User;
}

export interface Retoken {
    retoken: RetokenClass;
}

export interface RetokenClass {
    token: string;
    user:  User;
}
